version: "3.9"

services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle-free
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: pass            # used ONLY on first init of the DB
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: