version: '3.8'

services:
  web:
    image: harshksaw/lab4-flask:v8
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
