from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class DimDate(db.Model):
    __tablename__ = "dim_date"
    sk_date_id = db.Column(db.Integer, primary_key=True)
    datetime = db.Column(db.DateTime)
    date = db.Column(db.String(10))
    hour = db.Column(db.Integer)
    day_of_week = db.Column(db.Integer)
    day_name = db.Column(db.String(20))
    day_of_month = db.Column(db.Integer)
    day_of_year = db.Column(db.Integer)
    week_of_year = db.Column(db.Integer)
    month = db.Column(db.Integer)
    month_name = db.Column(db.String(20))
    quarter = db.Column(db.Integer)
    year = db.Column(db.Integer)
    fiscal_year = db.Column(db.Integer)
    is_weekend = db.Column(db.Boolean)

class DimCompany(db.Model):
    __tablename__ = "dim_company"
    sk_company_id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(50), unique=True, nullable=False)
    beta = db.Column(db.Numeric)
    vol_avg = db.Column(db.Numeric)
    mkt_cap = db.Column(db.Numeric)
    last_div = db.Column(db.Numeric)
    range = db.Column(db.String(50))
    changes = db.Column(db.Numeric)
    company_name = db.Column(db.String(255))
    currency = db.Column(db.String(10))
    cik = db.Column(db.String(50))
    isin = db.Column(db.String(50))
    cusip = db.Column(db.String(50))
    industry = db.Column(db.String(100))
    sector = db.Column(db.String(100))
    country = db.Column(db.String(100))
    full_time_employees = db.Column(db.Integer)
    city = db.Column(db.String(100))
    state = db.Column(db.String(100))
    ipo_date = db.Column(db.Date)
    is_actively_trading = db.Column(db.Boolean)
    pe_ratio_ttm = db.Column(db.Numeric)
    price_to_book_ratio_ttm = db.Column(db.Numeric)
    debt_to_equity_ratio_ttm = db.Column(db.Numeric)
    peg_ratio_ttm = db.Column(db.Numeric)
    return_on_equity_ttm = db.Column(db.Numeric)
    annual_free_cash_flow = db.Column(db.BigInteger)

class FactMarketMetrics(db.Model):
    __tablename__ = "fact_market_metrics"
    sk_market_metrics_id = db.Column(db.Integer, primary_key=True)
    fk_company_id = db.Column(db.Integer, db.ForeignKey("dim_company.sk_company_id"))
    fk_date_id = db.Column(db.Integer, db.ForeignKey("dim_date.sk_date_id"))
    fk_exchange_id = db.Column(db.Integer, db.ForeignKey("dim_exchange.sk_exchange_id"))
    fk_commodity_id = db.Column(db.Integer, db.ForeignKey("dim_commodity.sk_commodity_id"))
    fk_index_id = db.Column(db.Integer, db.ForeignKey("dim_index.sk_index_id"))
    fk_stock_id = db.Column(db.Integer, db.ForeignKey("dim_stock.sk_stock_id"))
    fk_bond_id = db.Column(db.Integer, db.ForeignKey("dim_bond.sk_bond_id"))
    current_price = db.Column(db.Numeric)
    change_percentage = db.Column(db.Numeric)
    change = db.Column(db.Numeric)
    day_low = db.Column(db.Numeric)
    day_high = db.Column(db.Numeric)
    year_high = db.Column(db.Numeric)
    year_low = db.Column(db.Numeric)
    market_cap = db.Column(db.Numeric)
    price_average_50 = db.Column(db.Numeric)
    price_average_200 = db.Column(db.Numeric)
    volume = db.Column(db.BigInteger)
    average_volume = db.Column(db.BigInteger)
    opening_price = db.Column(db.Numeric)
    previous_close = db.Column(db.Numeric)
    eps = db.Column(db.Numeric)
    pe = db.Column(db.Numeric)
    shares_outstanding = db.Column(db.BigInteger)
