version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cosc
      POSTGRES_PASSWORD: cosc436
      POSTGRES_DB: stock_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
















    ports:
      - "5432:5432"
    networks:
      - stock_analysis_net
  
  jupyter:
    build: .
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - stock_analysis_net
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - stock_analysis_net
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  stock_analysis_net: