version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cosc
      POSTGRES_PASSWORD: cosc436
      POSTGRES_DB: stock_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - stock_analysis_net
  python:
    image: jupyter/scipy-notebook:latest
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - stock_analysis_net
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  stock_analysis_net:
